[project]
name = "grandowl"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "grandowlgh", email = "tda0016@uah.edu" }
]
requires-python = ">=3.14"
dependencies = []

[tool.maturin]
module-name = "grandowl._core"
python-packages = ["grandowl"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[tool.uv.workspace]
members = [
    "matrix",
]


